name: Build Application

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x # Use a specific version or 'latest'

      - name: Compile
        run: deno task build

      - name: Chmod
        run: deno task chmod

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download compiled binaries
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Uses the tag that triggered the workflow
          name: Release ${{ github.ref_name }}
          body: |
            🚀 New release: **${{ github.ref_name }}**
            - Auto-generated release for version **${{ github.ref_name }}**
          draft: false
          prerelease: false
          files: |
            switch-branch-intel
            switch-branch
            switch-branch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
