name: Build Deno App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x # Use a specific version or 'latest'

      - name: Compile Deno App
        run: deno compile --allow-env --allow-run --target x86_64-apple-darwin --output branch-cli main.ts
      - name: Compile Deno App
        run: deno compile --allow-env --allow-run --target aarch64-apple-darwin --output branch-cli-arm main.ts
      - name: Compile Deno App
        run: deno compile --allow-env --allow-run --target x86_64-pc-windows-msv --output branch-cli.exe main.ts

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: deno-compiled-binary
          path: |
            branch-cli
            branch-cli-arm
            branch-cli.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: deno-compiled-binary
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Uses the tag that triggered the workflow
          name: Release ${{ github.ref_name }}
          body: |
            🚀 New release: **${{ github.ref_name }}**
            - Auto-generated release for version **${{ github.ref_name }}**
          draft: false
          prerelease: false
          files: |
            branch-cli
            branch-cli-arm
            branch-cli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
